package university.users;

import university.enums.ManagerType;
import university.academic.Course;
import university.communications.News;
import university.communications.Request;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

public class Manager extends Employee {

    private ManagerType managerType;

    public Manager(String id, String firstName, String lastName,
                   String email, String login, String passwordHash,
                   double salary,
                   ManagerType managerType) {
        super(id, firstName, lastName, email, login, passwordHash, salary, "Office of Registrar");
        this.managerType = managerType;
    }

    public void assignTeacher(Teacher teacher, Course course) {
        if (teacher == null || course == null) throw new IllegalArgumentException("Teacher and Course cannot be null.");
        course.addTeacher(teacher);
        teacher.addCourse(course);
        System.out.printf("[Manager %s] Assigned teacher '%s' to course '%s'.%n",
                getFullName(), teacher.getFullName(), course.getName());
    }

    public void approveRegistration(Student student, Course course) {
        if (student == null || course == null) throw new IllegalArgumentException("Student and Course cannot be null.");
        System.out.printf("[Manager %s] Approved registration of '%s' for course '%s'.%n",
                getFullName(), student.getFullName(), course.getName());
        course.enrollStudent(student);
    }


    public void addCourseForRegistration(Course course, String targetMajor, int yearOfStudy) {
        if (course == null) throw new IllegalArgumentException("Course cannot be null.");
        course.setTargetMajor(targetMajor);
        course.setTargetYear(yearOfStudy);
        course.setOpenForRegistration(true);
        System.out.printf("[Manager %s] Opened course '%s' for registration (major: %s, year: %d).%n",
                getFullName(), course.getName(), targetMajor, yearOfStudy);
    }


    public String createReport(List<Student> students) {
        if (students == null || students.isEmpty()) return "No students to report on.";

        StringBuilder sb = new StringBuilder();
        sb.append("=== Academic Performance Report ===\n");
        sb.append(String.format("Generated by: %s (%s)%n", getFullName(), managerType));
        sb.append(String.format("Total students: %d%n%n", students.size()));

        double totalGpa = 0;
        for (Student s : students) {
            sb.append(String.format("  %-30s GPA: %.2f  Credits: %d%n",
                    s.getFullName(), s.getGpa(), s.getTotalCredits()));
            totalGpa += s.getGpa();
        }

        double avg = totalGpa / students.size();
        sb.append(String.format("%nClass average GPA: %.2f%n", avg));
        sb.append("===================================\n");

        String report = sb.toString();
        System.out.print(report);
        return report;
    }


    public void manageNews(News news, List<News> newsFeed, NewsAction action) {
        switch (action) {
            case ADD    -> { newsFeed.add(news); System.out.printf("[Manager] News added: '%s'%n", news.getTitle()); }
            case REMOVE -> { newsFeed.remove(news); System.out.printf("[Manager] News removed: '%s'%n", news.getTitle()); }
            case UPDATE -> System.out.printf("[Manager] News updated: '%s'%n", news.getTitle());
        }
    }

    public void manageNews(News news, List<News> newsFeed) {
        manageNews(news, newsFeed, NewsAction.ADD);
    }

    
    public void viewStudentsSorted(List<Student> students, Comparator<Student> comparator) {
        System.out.printf("[Manager %s] === Student List ===%n", getFullName());
        students.stream()
                .sorted(comparator)
                .forEach(s -> System.out.printf("  %s | GPA: %.2f | Credits: %d%n",
                        s.getFullName(), s.getGpa(), s.getTotalCredits()));
    }

    public void viewStudentsByGpa(List<Student> students) {
        viewStudentsSorted(students, Comparator.comparingDouble(Student::getGpa).reversed());
    }

    public void viewStudentsAlphabetically(List<Student> students) {
        viewStudentsSorted(students, Comparator.comparing(User::getLastName));
    }

    public void viewTeachersSorted(List<Teacher> teachers, Comparator<Teacher> comparator) {
        System.out.printf("[Manager %s] === Teacher List ===%n", getFullName());
        teachers.stream()
                .sorted(comparator)
                .forEach(t -> System.out.printf("  %s | Position: %s | Rating: %.1f%n",
                        t.getFullName(), t.getPosition(), t.getRating()));
    }

    
    public void viewRequests(List<Request> requests) {
        System.out.printf("[Manager %s] === Incoming Requests ===%n", getFullName());
        if (requests.isEmpty()) {
            System.out.println("  No requests.");
            return;
        }
        requests.forEach(r -> System.out.printf("  [%s] %s — %s (submitted: %s)%n",
                r.getStatus(), r.getId(), r.getDescription(), r.getCreatedAt()));
    }

    public ManagerType getManagerType() {
        return managerType;
    }

    public void setManagerType(ManagerType managerType) {
        this.managerType = managerType;
    }

    @Override
    public String toString() {
        return String.format("Manager{id='%s', name='%s', type=%s, department='%s'}",
                getId(), getFullName(), managerType, getDepartment());
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj);
    }

    @Override
    public int hashCode() {
        return super.hashCode();
    }

    // Enum for news operation
    public enum NewsAction {
        ADD, REMOVE, UPDATE
    }
}